language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # docker image named as udagram-reverse-proxy for the current project .
  - docker build -t udagram-reverse-proxy .
  # tag the image called udagram-reverse-proxy to linhpvt/udagram-reverse-proxy:latest
  - docker tag udagram-reverse-proxy linhpvt/udagram-reverse-proxy:latest
after_success:
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push tagged image to docker hub
  - docker push linhpvt/udagram-reverse-proxy
  